### PR TITLE
Fix audit warnings and a little cleanup

### PR DESCRIPTION
**Pull request by hbroer**
Removed most of the dependencies because they are highly out of date and not used inside of this module.

The unit test was really senseless:
`assert.equal(false, !true);`

Maybe someone with no life will write a few real tests? ;)

### CODE REVIEW

**Comment by kthy** [comment]
I'd love to see this merged and a new version pushed to npm. @ me if I can do anything to help.

**Comment by brtx** [comment]
Sorry for taking that long, I merged and published it now. Please let us know if there are any issues, we don't really use TFS anymore and unfortunately as you saw we never took the time to write some proper tests.

**Comment by hbroer** [comment]
Hi, thanks for merging.

I will party hard if that crappy TFS got kicked out of my company ;) I understand your very little interest in that vcs :D

**Comment by brtx** [comment]
Hehe, thanks anyway for the fixes :-)

**Pull request merged**
