### PR TITLE
remove substring of timestamp

### PR DESCRIPTION
**Pull request by baptisteMillot**

### CODE REVIEW

**Comment by baptisteMillot** [comment]
remove error message from sonar VisualStudioTestResultsFileParser.java class with expected date format : "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"

**Comment by baptisteMillot** [comment]
Use Regex for what? I delete the substring to have the complete date in ISO string

**Comment by brtx** [comment]
I don't remember why I added the substr in the first place, I guess I just didn't care the ms. I guess we could just add those, but I am not sure if it may break any existing usages. So I would propose that we should add another config for adding the ms which defaults to the behaviour how it was from the beginning so we don't break anything.

**Comment by lehmamic** [comment]
Agree with you @brtx

**Comment by brtx** [comment]
This one is resolved also now with https://github.com/hatchteam/karma-trx-reporter/pull/17

**Pull request closed without merging**
